# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6287c29ade54d95c7eb53f5be042b32340931ad976c4f7ba91881f487f78893448225ad8d0cbd040d25176a8c0233fe02ef5dd20243e95277ff4e8316de56645

test:
  secret_key_base: dad4f4ed618826aa7428638d2c65d195967af8822c210ee060ac0be40971f706b37126631e53988c1580ddd95d73cd70e30ce3aba229ce10f2c2410a0e451ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
